### ISSUE TITLE
Make reach a gamerule?

### ISSUE THREAD

**Issue by Matthias1590** [RedstoneTools/redstonetools-mod#80]
It probably shouldn't be a gamerule but for now it can be so we don't have to deal with saving and loading to and from disk

**Comment by MiranCZ** [comment]
Why would we load from disk?

**Comment by Matthias1590** [comment]
Having to set the reach every time you boot the game will get really annoying

**Comment by RUGMJ** [comment]
if were having an overlay on where you're going to place the block couldn't we just use the mouse wheel to change the distance? And have a default value of 3 or 5 blocks?

**Comment by Matthias1590** [comment]
> if were having an overlay on where you're going to place the block couldn't we just use the mouse wheel to change the distance? And have a default value of 3 or 5 blocks?

no, the mouse wheel is already in use and being able to just set the players reach is easier

**Comment by JayMensink** [comment]
Will see what I can do!

**Comment by JayMensink** [comment]
UPDATE: Configurable AirPlace Reach is gonna have to be tied to the command rather than a new gamerule.

AirPlace is handled using the `doItemUse` method. This method is called client-side, while gamerules are handled server-side. This is a problem because the client does not have access to the gamerules (unless the player is playing in Single Player).

Usage of gamerules is a bad idea in case we decide to fully support multiplayer in the future.

**Comment by AvisNF** [comment]
I am not shure if it is bad but you could just put simple informations like reach in the NBT data of the player.

**Comment by JayMensink** [comment]
Merged. Please close this issue @Matthias1590
